server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

logging:
#  file: log/order_sync.log
  level:
    root: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN

spring:
  application:
    name: pet-store
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    initialization-mode: always
    schema: classpath:schema.sql
    data: classpath:data.sql
    data-username: sa
    data-password: password
  jpa:
    hibernate:
      ddl-auto: update